name: CI

on:
  push:
    branches:
      - master
    tags: [ 'v*' ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint with Gradle
        run: ./gradlew checkstyleMain checkstyleTest spotbugsMain spotbugsTest pmdMain pmdTest javadoc --stacktrace --no-daemon

      - name: Annotate Checkstyle Issues
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/build/reports/checkstyle/*.xml'

      - name: Annotate SpotBugs Issues
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/build/reports/spotbugs/*.xml'

      - name: Annotate PMD Issues
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/build/reports/pmd/*.xml'

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test --stacktrace --no-daemon

  build:
    needs: [ lint, test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew installDist --stacktrace --no-daemon

      - uses: actions/upload-artifact@v2
        with:
          name: GdP
          path: build/install/GdP
